### ISSUE TITLE
TODO - Manuscript Task: Verify Hypothyroidism Phenotype

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowVec#18]
Creating as a separate issue to break-up **issue** #2 

**Finalizing the [Hypothyroidism Phenotype](https://github.com/callahantiff/PheKnowVec/wiki/Hypothyroidism)**

> **Case Criteria:**
> - Presence of hypothyroidism ICD9 codes OR Abnormal TSH (>5.0) or FT4 (<0.5) lab results (lab code)
> - Presence of thyroid replacement medication (medication string)
> - Require > 2 instances of either medication or lab (or combination) with > 3 months between the first and last instance of medication or lab
> - NOT presence of secondary causes of hypothyroidism (ICD9 code)
> - NOT presence of other thyroid diseases by IC9 codes or CPT codes
> - NOT presence of certain thyroid diseases (condition or procedure keyword)
> - NOT presence of pregnancy ICD9 codes and an abnormal TSH or FT4 (lab code) 6 mon (before)-1 yr (after) birth 
> - NOT presence of abnormal b-HCG labs and an abnormal TSH or FT4 (lab code) 6 mon (before)-1 year (after) birth 
> - NOT presence of recent contrast exposure (all abnormal lab or medication instances within 6 weeks of a contrast study) (labs and/or medication keyword)
> - NOT presence of ANY radiation therapy code (if it proceeds hypothyroidism) (CPT code)
> - NOT presence of ANY Thyroidectomy code (CPT code)
> - NOT presence of ANY thyroid-altering medication (medication string)
> 
> <br>
> 
> **Control Criteria:**
> - Have a normal TSH (0.5 – 5) and normal FT4 (0.5-1.2) (lab code)
> - Presence of > 2 past medical history sections and medication lists (could substitute two non-acute clinic visits or annual physical)
> - NOT presence of ANY billing codes for hypothyroidism (ICD9 code)
> - NOT presence of ANY evidence of thyroid replacement medications (medication string)
> - NOT presence of ANY cause of hypothyroidism or hyperthyroidism
> - NOT presence of ANY radiation therapy code (if it proceeds hypothyroidism) (CPT code)
> - NOT presence of ANY thyroidectomy code (CPT code)
> - NOT presence of certain thyroid diseases (condition or procedure keyword)
> - NOT presence of ANY thyroid-altering medication (medication string)

____

**Questions:**
**LABS: Given the description, have I selected the correct LOINC code?**
- [x] TSH and FT4 Labs: 

Source | LOINC
-- | -- 
Both | 3016-3: Thyrotropin [Units/volume] in Serum or Plasma
Both | 3024-7: Thyroxine (T4) free [Mass/volume] in Serum or Plasma
Both | 3026-2: Thyroxine (T4) [Mass/volume] in Serum or Plasma
Both | 32215-6: Thyroxine (T4) free index in Serum or Plasma by calculation
DS 1 | 29575-8: Thyrotropin [Units/volume] in DBS
DS 1 | 3021-3: Thyroxine binding globulin [Mass/volume] in Serum or Plasma
DS 1 | 31144-9: Thyroxine (T4) [Mass/volume] in DBS
DS 1 | 5385-0: Thyrotropin receptor Ab [Units/volume] in Serum
DS 1 | 6892-4: Thyroxine (T4) free [Mass/volume] in Serum or Plasma by Dialysis
DS 2 | 3027-0: Thyroxine (T4)/Thyroxine binding globulin [Mass Ratio] in Serum or Plasma
<br>

- [x] Anti-thyroglobulin antibodies: H-TGA, ThyrAB, AThyg-positive

Source | LOINC
-- | -- 
Both | 3013-0: Thyroglobulin [Mass/volume] in Serum or Plasma
DS 1 | 8098-6: Thyroglobulin Ab [Units/volume] in Serum or Plasma
DS 2 | 5380-1: Thyroglobulin Ab [Units/volume] in Serum by Radioimmunoassay (RIA)
<br>

- [x] Anti-thyroperoxidase: H-TPO, TPO, AThyP-positive

Source | LOINC
-- | -- 
Both | 8099-4: Thyroperoxidase Ab   [Units/volume] in Serum or Plasma
DS 2 | 32042-4: Thyroperoxidase Ab [Presence] in Serum or Plasma
<br>

- [x] Anti-thyroid antibodies: ThyAb-positive (don't think this is the correct lab)

Source | LOINC
-- | -- 
DS 1 | 30567-2: Thyroid stimulating   immunoglobulins [Units/volume] in Serum
<br>

- [x] Urine or serum b-HCG

Source | LOINC
-- | -- 
DS 1 | 2112-1: Choriogonadotropin.beta   subunit (pregnancy test) [Presence] in Urine
DS 2 | 21198-7: Choriogonadotropin.beta subunit [Units/volume] in   Serum or Plasma

***

- [x] One of the control criteria mentioned above states, "presence of >2 past medical history sections and medication lists (could substitute two non-acute clinic visits or annual physical)". Does that mean to be eligible, a patient needs to have at least 2 medications and 2 visits or, to be considered a "medical history section" does it need to be a visit where a diagnosis occurs?

<br>

- [x] Another control criteria states, "NOT presence of ANY cause of hypothyroidism or hyperthyroidism". This seems more involved than just looking for occurrences of "hyperthyroidism" or "hypothyroidism", or am I overthinking it?

<br>

***

@tdbennett, can you please advise on these questions?
