### ISSUE TITLE
TODO - Manuscript Task: Verify Appendicitis Phenotype

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowVec#22]
Creating as a separate issue to break-up **issue** #2 

**Finalizing the [Appendicitis Phenotype](https://github.com/callahantiff/PheKnowVec/wiki/Appendicitis)**

> **Case Criteria:**
> -  CASE TYPE 1 - "Pathology report positive for appendicitis" (_don’t have this data_)
>
> <br>
>
> - CASE TYPE 2a - No pathology report, treatment is systemic antibiotics
>   - Presence of an appendicitis diagnosis (ICD9 code)
>   - Presence of systemic antibiotics (>2 days treatment, starting on encounter of appendicitis diagnosis) (medication string)
>   - NOT presence of an appendicitis comorbidity in same encounter as appendicitis diagnosis (ICD9 code)
>   - NOT presence of an interventional Radiology code (CPT code)
>
> <br>
>
> - CASE TYPE 2b - No pathology report, treatment is interventional radiology
>   - Presence of an appendicitis diagnosis (ICD9 code)
>   - Presence of an interventional Radiology code (CPT code) 
>   - NOT presence of an appendicitis comorbidity in same encounter as appendicitis diagnosis (ICD9 code)
>   - NOT Presence of systemic antibiotics (>2 days treatment, starting on encounter of appendicitis diagnosis) (medication string)
>
> <br>
>
> - CASE TYPE 3 - "Reported history of appendicitis or appendectomy, no history of incidental appendectomy"
>   - Presence of history of appendicitis reported (observation keyword search)
>   - NOT Presence of an incidental appendectomy (CPT code/ICD9 code)
>
> <br>
>
> **Control Criteria:**
> - CONTROL TYPE 1 - Pediatric patients
>   - NOT presence of history of appendicitis reported (observation keyword search)
>   - NOT presence of an appendicitis diagnosis (ICD9 code)
>   - NOT presence of exclusionary codes (ICD9 code)
>
> <br>
>
> - CONTROL TYPE 2 - Adult patients
>   - Presence of at least 2 primary care/medical home visits between ages 20-40 years (inclusive)
>   - NOT presence of history of appendicitis reported (observation keyword search)
>   - NOT presence of an appendicitis diagnosis (ICD9 code)
>   - NOT presence of exclusionary codes (ICD9 code)
____

**Questions:**
- [x] There are several case types for this phenotype (see above). We have data for types 2 and 3, but not for type 1. I am including this here so you are aware.

<br>

- [x] We will have separate control group definitions for pediatric and adult patients. Given the selection criteria, I will search for both types of control patients in both data sources. Do you agree with this?

<br>

- [x] Related to the prior question, what do we consider "primary care/medical home"?
 - Visit Admitting Type:
    - Hospitals, General Acute Care Hospital
    - Other
    - Ambulatory visit
    - Hospice
    - Emergency Room - Hospital 
    - Skilled Nursing Facility
    - Home / self care

<br>

  - Care Site:
    - Outpatient Hospital
    - Urgent Care Facility
    - Emergency Room - Hospital
    - Other
    - Inpatient Psychiatric Facility
    - Inpatient Hospital
    - Other Place of Service

<br>

- [x] There is a case/control criteria that requires inclusion or exclusion of patients with "history of appendicitis". Is the presence of the code shown below sufficient to meet this criteria or, do I need to search for any occurrence of "appendicitis" in any table?

code | name | vocabulary_id | domain_id
-- | -- | -- | --
161532008 | H/O: appendicitis | SNOMED | Observation

<br>

***

@tdbennett, can you please advise on these questions?
