### ISSUE TITLE
Project Meeting -- 03/07/2019 @ 13:00

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowVec#24]
**Meeting Date:** Thursday, March 7th, 2019  
**Topic:** PheKnowVec Evaluation  
**Attendees:** @tdbennett 

**Proposed Agenda:**
Dr. Bennett and I met today to discuss the first PheKnowVec manuscript. The goals of the meeting today were:  
- Talk about the experimental evaluation plan for the manuscript; see #5  
    - [X] We discussed what experiments were planned for each of the three barriers (i.e. generalizability, translatability, and scalability). The plan for each barrier has been updated in the [analysis and evaluation plan](https://github.com/callahantiff/PheKnowVec/wiki/Initial-Manuscript%3A-Analysis-and-Evaluation-Plan).  
    - [X] I am going to create a simple figure that provides an overview of each planned experiment. It is my intention that this figure can be used to help structure the code and explain our approach to collaborators and/or future users of the method (hopefully 😄). 
- Discuss my plan to use this GitHub repository as a project management tool (in an effort to make this project more reproducible).  
    - [X] Dr. Bennett is onboard with plan for using repository for tracking project process, asking questions, and specifying tasks to be completed (in addition to using it for version control of code).  
    - [X] I will add other advisors to the repository later today.

**TODO:**  
- [X] Generate figure to help explain experimental evaluation; see #8 
- [X] Add co-authors from NLM abstract as collaborators to project and list on Wiki homepage; see #10 

****
@tdbennett no need to respond adding this to archive our meeting. I am updating some aspects of repository and how I want to use it for reproducibility, given feedback I received this week.
***
