### ISSUE TITLE
Project Meeting -- 03/12/2019 @ 13:30

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowVec#25]
**Meeting Date:** Tuesday, March 12th, 2019  @ 13:30
**Topic:** General PheKnowVec Updates  
**Attendees:** @mgkahn 

**Proposed Agenda:**
- [X] Review repository: [Projects](https://github.com/callahantiff/PheKnowVec/projects), [issues](https://github.com/callahantiff/PheKnowVec/issues), [Wiki](https://github.com/callahantiff/PheKnowVec/wiki)
  - We went through the different aspects of the GitHub repository together and discussed how I intended to use this as a reproducible research repository.
    - I created some [documentation](https://github.com/callahantiff/PheKnowVec/wiki/Using-GitHub-as-a-Reproducible-Research-Platform) to help my collaborators understand how to use the various GitHub functionality needed for this project
     - I also started drafting [reproducibility guidelines](https://github.com/callahantiff/PheKnowVec/wiki/My-Reproducible-Repository-Guidelines-%F0%9F%98%83) on using the repository in a reproducible manner
- [X] Go over [experimental design plan](https://github.com/callahantiff/PheKnowVec/wiki/Initial-Manuscript:-Analysis-and-Evaluation-Plan)
  - Dr. Kahn and I were unable to go through every aspect of the evaluation plan. He has agreed to review the wiki and provide feedback, see TODO item below
- [X] Finalize phenotype documentation and code sets; see **issue** #2 
  - Dr. Kahn and I went through some of the documentation so I could verify that the approach I was taking for representing the phenotype logic was correct. My initial approach has been approved, but I will periodically verify it during our upcoming standing meetings.
- [X] Discuss pros/cons of clinical validation plan for small subset of phenotypes 
  - We have decided that we will not initially pursue chart-review as validation and will instead try to rely on using the patient's full record in the de-identified data set. If reviewers request a more extensive review, we will pursue IRB approval for having a small subset of the results validated. Additionally, we have decided that we will discuss this again once we have some initial results generated. If the results are very promising, we will set a meeting with [Sara Deakyne Davies](https://github.com/saradeakyne) to get her feedback on our plan. If this is approved, we will move forward with submitting an IRB proposal. See **issue** #23 
- [X] Discuss running CHCO DEID and MIMIC 3 OMOP on GCP VPNs; see **issue** #6
  - This should be fine, assuming that we do not violate any of our agreements with CHCO. Dr. Kahn and I will meet with @saradeakyne once we are closer to being ready to run the analyses, to verify the details of approach for processesing data on GCP VPNs.

***
**TODO:**  
- [x] Draft SQL queries to generate case/control cohorts for each phenotype
- [X] Send Dr. Kahn link to analysis plan for review (sent via **issue** #5 on 03/13/19)
***
