### ISSUE TITLE
TODO: Investigate potential DQ issues

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowVec#33]
**NOTES --  Related to Querying the Data Sources, that Need to be Fixed:**
- [ ] The mappings reported for source code ICD9-CM 318 differed between the data sources when mapping this source code to SNOMED (via OMOP vocabulary mappings):
     - Data Source 1 reported 91138005 (“Mental retardation”) —> this term has been replaced in OMOP vocabulary documentation by 110359009 ("Intellectual disability")
      - Data Source 2 reported 110359009 (“Intellectual developmental disorder”) —> this is the right concept with the wrong label (“Intellectual developmental disorder” is a synonym), the correct label is "Intellectual disability”  

<br>

- [ ] ICD9 codes 781.2 and 781.91 map to SNOMED concepts (via OMOP vocabulary mappings) as observations rather than the conditions. We may need to change the search criteria when writing the queries and remove domain_id=“condition” and instead, only use vocabulary_id="SNOMED"

<br>

- [ ] ICD9-CM 295.03 is mapped to an inactive term, but Data Source 1 reported 191530008 ("Acute exacerbation of subchronic schizophrenia") , which is an inactive term and should be updated to 111482003 ("Subchronic schizophrenia with acute exacerbations")

<br>

- [ ] ICD9-CM 296.35 should be mapped to SNOMED 68019004, but is not for either data source:
    - Data Source 1 reported 191615005 ("Recurrent major depressive episodes, in full remission")
    - Data Source 2 reported 46244001 ("Recurrent major depression in full remission")

<br>

- [ ] ICD9-CM 312 should be mapped to SNOMED 430909002, but for Data source 1, this term is mapped to 110359009 ("Intellectual disability") and 430909002 ("Conduct disorder")

<br>

- [ ] ICD9-CM 313 should be mapped to SNOMED 268664001,  but for Data source 1, this term is mapped to 110359009 ("Intellectual disability") and 268664001 ("Childhood emotional disorder")

<br>

- [ ] ICD9-CM 315 should be mapped to SNOMED 10720004,  but for Data source 1, this term is mapped to 110359009 ("Intellectual disability") and 10720004 ("Specific developmental disorder")

<br>

- [ ] ICD9-CM 758.32 should be mapped to SNOMED 767263007, but is not for either data source:
    - Data Source 1 reported 83092002 ("Shprintzen syndrome"), which is noted in Athena to be replaced with 767263007 ("22q11.2 deletion syndrome")
    - Data Source 2 reports the correct ID, but has an incorrect label

_Originally posted by @callahantiff in https://github.com/callahantiff/PheKnowVec/issues/21#issuecomment-473711785_
