### ISSUE TITLE
Project Meeting -- 05/07/2019 @ 13:00

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowVec#38]
**Meeting Date:** 05/07/2019 @ 13:00
**Topic:** Code Set Analysis + Expert/Student verification
**Attendees:** @mgkahn

**Proposed Agenda:** I'd like to follow-up on the subjects discussed last week including discussing the criteria for student review of source concepts.
______
**UPDATE:** 
* [x]  Update information on code sets, and our motivation for doing this work [here](https://github.com/callahantiff/PheKnowVec/wiki/Code-Sets).

I have been working on building each of the code sets for the phenotypes that contain input source strings (click on each phenotype to see a results dashboard):
* **ADHD** ([Dashboard](https://docs.google.com/spreadsheets/d/1yF-sXVIY5Bzsq9fIR765e4xPcQmmsWn7nXrDZu46uMg/edit#gid=0); [Code Sets](https://drive.google.com/open?id=1jD7hnGGYDuCnh1Fu7dN29xizgwlQIX3z))
   * [x]  Drug

 * **Appendicitis** ([Dashboard](https://docs.google.com/spreadsheets/d/107L3S9WCmhAyHBTf0757ZYvjOoLckIf0yCj4WblEVk8/edit#gid=0); [Code Sets](https://drive.google.com/open?id=1Em3Zf7HeHGs8hkclmf3xTtwKcITDfB-w))
   * [x] Condition
   * [x]  Drug
   * [x]  Observation

 * **Crohn's Disease** ([Dashboard](https://docs.google.com/spreadsheets/d/1iA7GrCp4mKEqaLkZpS8JovYDn0djhBjPr4Ri1RRyDhY/edit#gid=0); [Code Sets](https://drive.google.com/open?id=1BEcRczWN2EqlojfSVkSs5LHUPVxo0C08))
   * [x]  Condition
   * [x]  Drug

 * **Hypothyroidism** ([Dashboard](https://docs.google.com/spreadsheets/d/1TVDeDvh1lsDm_ZB_EMa_XUMOQE5oNtOM_NgKA1W6kW0/edit#gid=0); [Code Sets](https://drive.google.com/open?id=1Nrc-36MwJ_vZj1JiRBiPGrhPvhc6kDKm))
   * [x]  Condition
   * [x]  Drug
   * [x]  Measurement
   * [x]  Observation
   * [x]  Procedure

 * **Peanut Allergy** ([Dashboard](https://docs.google.com/spreadsheets/d/1KkCWi_KEjvKKvtnJixjgDlTQkv8vm-ljzPG-9oy9cJc/edit#gid=0); [Code Sets](https://drive.google.com/open?id=1v71bgKnKNVZOeJ1x8jIhwq-jtP_4RXrn))
   * [x]  Condition
   * [x]  Drug
   * [x]  Measurement
   * [x]  Observation
   * [x]  Procedure

 * **Steroid-Induced Osteonecrosis** ([Dashboard](https://docs.google.com/spreadsheets/d/1ULgyePGZD1AVcef89XYPvdhjs21QqT3nR4c9jX_egwg/edit#gid=0); [Code Sets](https://drive.google.com/open?id=17nJx18n_JIc-zP0VD1CuVxyyhiMv4cXZ))
   * [x]  Condition
   * [x]  Drug
   * [x]  Measurement
   * [x]  Observation
   * [x]  Procedure

 * **Systemic Lupus Erythematosus** ([Dashboard](https://docs.google.com/spreadsheets/d/19CogiNlkHPjUcD6M-oUiw0kmEdO3hLlLzSeV2O2GWZ4/edit#gid=0); [Code Sets](https://drive.google.com/open?id=1GCbK5tMxFMX7XesMHmdHi1zvyi50AaWe))
   * [x]  Condition
   * [x]  Drug
   * [x]  Measurement

**Specific Questions related to code sets:**
- [x] Do we want to reduce the spreadsheets so that only the rows with at least 1 occurrence in either CHCO or OMOP-MIMICIII? NO, we will include all rows that have a source to standard code mapping.
______

**OTHER THINGS TO DISCUSS**
* Develop more formal plan for verifying the code sets
   * Student Evaluators
     * [x]  Number and type of pharmacy students (n=2)
     * [x]  Number and type of medical students (n=2 third year student past STEP)
   * Expert review
   * Formalize Both Tasks
     * [x]  Develop checklist with workflow and example, draft started [here](https://paper.dropbox.com/doc/PheKnowVec-Code-Set-Verification-Medications--Acr6pCbNRPlzu73vjMgyRajgAg-9mN6J3C89LRrZxt1RVeGy)
     * [ ]  Time line
       
* Verifying code sets
   * Resolving uncertainties and discrepancies
     * [x]  Set-up Github-based system for verification, comments/questions and expert review. See [Project Board](https://github.com/callahantiff/PheKnowVec/projects/7).

____

**TODO:**
 - [ ] Verify checklist with Katy
 - [ ] Add Katy to GitHub repo
 - [ ] Finalize students and add to GitHub
