### ISSUE TITLE
Medication Source Code Verification: Student 2

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowVec#42]
**Student (GitHub Username):** @avnmatre 
**Verification Number:** 2

**Assigned Domain Expert:** @trinklek 

**Verification Task Description:** [DropBox Paper Documentation](https://paper.dropbox.com/doc/PheKnowVec-Medication-Code-Set-Verification--AdEKpNBr6AohQWEcdKuSEmVHAg-9mN6J3C89LRrZxt1RVeGy)

**Phenotype Descriptions:** [project wiki](https://github.com/callahantiff/PheKnowVec/wiki/Phenotypes)

**Verification Assignments:**
**UPDATE:** counts below updated to reflect [today's meeting](https://github.com/callahantiff/PheKnowVec/issues/56#issuecomment-500696981).

**Verification Assignments:**
  - [x] ADHD (~n=34,184~ n=6,837) -- #41  (completed by AVM)
  - [ ] Appendicitis (~n=15,304~ n=3,061) -- #45 
  - [ ] Crohn’s Disease (~n=17,887~ n=3,577) -- #47
  - [ ] Hypothyroidism (~n=15,243~ n=3,049) -- #48
  - [ ] Peanut Allergy (n=57) -- #53 
  - [ ] Steroid-Induced Osteonecrosis (~n=39,099~ n=7,820) -- #54
  - [ ] Systemic Lupus Erythematosus (~n=23,816~ n=4,763) -- #55
